version: '3'

services:
  c_base:
    container_name: c_base
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ./:/app
    init: true
